// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/coderyw/easymap/gen"

  pkg "github.com/coderyw/easymap/test/model"
)

func main() {
  g := gen.NewGenerator("model_easymap.go")
  g.SetPkg("model", "github.com/coderyw/easymap/test/model")
  g.Add(pkg.EasyMAP_exporter_Resp360(nil))
  g.Add(pkg.EasyMAP_exporter_Struct2(nil))
  g.Add(pkg.EasyMAP_exporter_TestStruct(nil))
  g.Add(pkg.EasyMAP_exporter_WaitGroupWrapper(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
