// 12121212
//

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/coderyw/easymap/gen"

	pkg "github.com/coderyw/easymap/test/model"
)

func main() {
	g := gen.NewGenerator("model_easymap.go")
	g.SetPkg("model", "github.com/coderyw/easymap/test/model")
	g.Add(&pkg.Resp360{})

	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
